# Generated by Django 2.2.16 on 2023-02-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можно загрузить файл с иллюстрацией', upload_to='posts/', verbose_name='Иллюстрация'),
        ),
    ]
